version: '3.4'

services:
  angularclient:
    image: angularclient
    build:
      context: src/Clients/Angular/AngularClient
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4200:4200
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
